const defaultConfig                                = require('@wordpress/scripts/config/webpack.config');
const {
		  requestToExternal,
		  requestToHandle,
		  getFile,
		  getWebPackAlias,
	  }                                            = require('./webpack-helpers');
const WooCommerceDependencyExtractionWebpackPlugin = require('@woocommerce/dependency-extraction-webpack-plugin');
const RemoveEmptyScriptsPlugin                     = require('webpack-remove-empty-scripts');

// Import the helper to find and generate the entry points in the src directory
const {getWebpackEntryPoints} = require('@wordpress/scripts/utils/config');

module.exports = {
	...defaultConfig,
	entry : {
		...getWebpackEntryPoints(),
		// 'product/index': getFile('product/index.js')
	},

	resolve : {
		...defaultConfig.resolve,
		alias : {
			...defaultConfig.resolve.alias,
			...getWebPackAlias(),
		},
	},

	plugins : [
		...defaultConfig.plugins.filter(
			(plugin) =>
				plugin.constructor.name !== 'DependencyExtractionWebpackPlugin'
		),
		new WooCommerceDependencyExtractionWebpackPlugin(
			{
				requestToExternal,
				requestToHandle,
			}
		),
		// Removes the empty `.js` files generated by webpack but
		// sets it after WP has generated its `*.asset.php` file.
		new RemoveEmptyScriptsPlugin(
			{
				stage : RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
			}
		),
	],
	/*	optimization: {
		runtimeChunk: { name: 'utils' },
	},*/
};
